app = 'evoagentx-server'
primary_region = 'sea'

[env]
  LOG_LEVEL = 'warning'
  SUPPRESS_WARNINGS = 'true'
  VERBOSE_STARTUP = 'false'

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '10m'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'
    protocol = 'http'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1 