site_name: EvoAgentX
theme:
  name: material
  font:
    text: Exo 2
    code: Fira Code
  icon:
    logo: material/robot
  # favicon: assets/logo.png
  features:
    - navigation.sections 
    - navigation.expand 
    - navigation.path
    - content.code.select
    - content.code.copy 
    - navigation.expand
    - navigation.instant
    - content.code.annotate
    - content.heading.auto-number  
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: teal
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

  # icon:
  #   repo: fontawesome/brands/github

repo_url: https://github.com/EvoAgentX/EvoAgentX
repo_name: EvoAgentX
repo_type: github

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EvoAgentX/EvoAgentX

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition

nav:
  - Getting Started:
    - About: index.md
    - Install: installation.md 
    - Quickstart: quickstart.md
  - Tutorials:
    - Build Your First Agent: tutorial/first_agent.md
    - Build Your First Workflow: tutorial/first_workflow.md
    - Benchmark and Evaluation: tutorial/benchmark_and_evaluation.md
    - SEW Optimizer: tutorial/sew_optimizer.md
  - Key Modules:
    - LLM: modules/llm.md 
    - Agent: modules/agent.md
    - Customize Agent: modules/customize_agent.md
    - Workflow Graph: modules/workflow_graph.md
    - Action Graph: modules/action_graph.md
    - Benchmark: modules/benchmark.md 
    - Evaluator: modules/evaluator.md 
  - API Reference:
    - Core: api/core.md
    - Models: api/models.md
    - Agents: api/agents.md
    - Workflow: api/workflow.md
    - Storages: api/storages.md
    - Memory: api/memory.md
    - Tools: api/tools.md 
    - Actions: api/actions.md
    - Benchmark: api/benchmark.md
    - Evaluators: api/evaluators.md
    - Optimizers: api/optimizers.md

# plugins:
#   - search
#   - mkdocstrings:
#       default_handler: python

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 3
            show_root_heading: true
            show_source: false
            merge_init_into_class: true
            show_signature: true
            show_docstring: true
            separate_signature: true
            members_order: source


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg