version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/
      - DATABASE_NAME=llm_agent_platform
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mongo
      - redis
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build: .
    command: celery -A app.services.execution_service.celery worker --loglevel=info
    environment:
      - MONGODB_URL=mongodb://mongo:27017/
      - DATABASE_NAME=llm_agent_platform
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - api
      - redis
      - mongo
    volumes:
      - ./app:/app/app

volumes:
  mongo_data:
  redis_data: